dialog:
  preview: "Preview"
  confirm: "Confirm"
  cancel: "Cancel"
  difference-warning: |
    <red>Warning!
    You are missing permissions for some formatting Tags.
    Your resulting rename will be different than the original!
  item-name:
    title: "Rename Item"
    info:
      - ""
    preview: "<ref:dialog.preview>"
    difference-warning: "<ref:dialog.difference-warning>"
    confirm: "<ref:dialog.confirm>"
    cancel: "<ref:dialog.cancel>"
    label: "Item Name"
  custom-name:
    title: "Rename Item Name"
    info:
      - ""
    difference-warning: "<ref:dialog.difference-warning>"
    preview: "<ref:dialog.preview>"
    confirm: "<ref:dialog.confirm>"
    cancel: "<ref:dialog.cancel>"
    label: "Item Name"
  lore:
    title: "Rename Lore"
    info:
      - ""
    difference-warning: "<ref:dialog.difference-warning>"
    preview: "<ref:dialog.preview>"
    confirm: "<ref:dialog.confirm>"
    cancel: "<ref:dialog.cancel>"
    label: "Item Lore"
